    days = ["On the first day of Christmas my true love gave to me: ",
            "On the second day of Christmas my true love gave to me: ",
            "On the third day of Christmas my true love gave to me: ",
            "On the fourth day of Christmas my true love gave to me: ",
            "On the fifth day of Christmas my true love gave to me: ",
            "On the sixth day of Christmas my true love gave to me: ",
            "On the seventh day of Christmas my true love gave to me: ",
            "On the eighth day of Christmas my true love gave to me: ",
            "On the ninth day of Christmas my true love gave to me: ",
            "On the tenth day of Christmas my true love gave to me: ",
            "On the eleventh day of Christmas my true love gave to me: ",
            "On the twelfth day of Christmas my true love gave to me: "]
    gifts = ["a Partridge in a Pear Tree.",
             "two Turtle Doves, and ",
             "three French Hens, ",
             "four Calling Birds, ",
             "five Gold Rings, ",
             "six Geese-a-Laying, ",
             "seven Swans-a-Swimming, ",
             "eight Maids-a-Milking, ",
             "nine Ladies Dancing, ",
             "ten Lords-a-Leaping, ",
             "eleven Pipers Piping, ",
             "twelve Drummers Drumming, "]
    recite = [f"{days[end_verse-1]}{gifts[start_verse-1:end_verse]}"]
